### ISSUE TITLE
Request: Add some topics to this repo

### ISSUE THREAD

**Issue by chmac** [0xtrr/nostr-tool#11]
Just discovered this repo by searching the domains of public nostr relays. Would you be open to adding the nostr topic to the repo? That would make it easier for folks to discover the repo on GitHub.

I'm browsing around the nostr landscape trying to get a sense of what's happening in the space, so I noticed that this repo didn't show up when I was looking at the topic here https://github.com/topics/nostr

**Comment by 0xtrr** [comment]
Good point, didn't even think of that. I have updated the repo now, thanks @chmac!
