### ISSUE TITLE
feat: Mine public keys

### ISSUE THREAD

**Issue by 0xtrr** [0xtrr/nostr-tool#4]
Add support for mining public keys. Tools such as [Rana](https://github.com/grunch/rana) and [Nostril](https://github.com/jb55/nostril) already has this feature but it would be nice to have it here as well.

**Comment by yukibtc** [comment]
I just added `vanity` feature in `nostr` and `nostr-sdk` crates so, in the next release, can  be added easly also in `nostr-tools`.

**Comment by 0xtrr** [comment]
Nice, when are you planning on publishing the next release @yukibtc?

**Comment by yukibtc** [comment]
> Nice, when are you planning on publishing the next release @yukibtc?

I think in a week or less.
I you want to test it, you can replace temporarily 

```toml
nostr-sdk = { version = "0.17", features = ["blocking"] }
```
with 

```toml
nostr-sdk = { git = "https://github.com/rust-nostr/nostr", rev = "77f631e85ef3b5c08b3387e4c80859a754e878f2", features = ["blocking"] }
```
