### ISSUE TITLE
delete-profile doesn't work

### ISSUE THREAD

**Issue by SilberWitch** [0xtrr/nostr-tool#62]
I just get an error message that the command doesn't work, and a suggestion to use delete-event, instead.

**Comment by SilberWitch** [comment]
I tried using delete-event with my script, but it changes the noteID with every iteration through the list of relays. 

Here is the input and output to the command line, from the loop, for the event with note1923tjys6pk2xc2j0rahnmn82ynghv4a5z0p0s2a7zw5l9cfhxm6qfsl8jq:

_nostr-tool -r wss://relay.damus.io -p [mynsec] delete-event -e 2aa2b9121a0d946c2a4f1f6f3dccea24d17657b413c2f82bbe13a9f2e13736f4_
Private key: [mynsec]
Public key: npub1qfkcklnmes45z75y7y8dkud5yll8vp5eq5ysk9rmgqdxeasv8unsrfj6kq
Deleted event with id: **note1w28zkq2txjdxd446aav5h44rcrwenrttju5sek5x5gjuwwumqhgq52e6gs**

_nostr-tool -r wss://relay.nostr.band -p [mynsec] delete-event -e 2aa2b9121a0d946c2a4f1f6f3dccea24d17657b413c2f82bbe13a9f2e13736f4_
Private key: [mynsec]
Public key: npub1qfkcklnmes45z75y7y8dkud5yll8vp5eq5ysk9rmgqdxeasv8unsrfj6kq
Deleted event with id: **note1w28zkq2txjdxd446aav5h44rcrwenrttju5sek5x5gjuwwumqhgq52e6gs**

_nostr-tool -r wss://relay.primal.net -p [mynsec] delete-event -e 2aa2b9121a0d946c2a4f1f6f3dccea24d17657b413c2f82bbe13a9f2e13736f4_
Private key: [mynsec]
Public key: npub1qfkcklnmes45z75y7y8dkud5yll8vp5eq5ysk9rmgqdxeasv8unsrfj6kq
Deleted event with id: **note1hj6xe7v7a6msu37cwjzzln87gjkx0q9sqdvqj5rts0y68zzd3vqqzn2x7d**

_nostr-tool -r wss://nos.lol -p [mynsec] delete-event -e 2aa2b9121a0d946c2a4f1f6f3dccea24d17657b413c2f82bbe13a9f2e13736f4_
Private key: [mynsec]
Public key: npub1qfkcklnmes45z75y7y8dkud5yll8vp5eq5ysk9rmgqdxeasv8unsrfj6kq
Deleted event with id: **note1hj6xe7v7a6msu37cwjzzln87gjkx0q9sqdvqj5rts0y68zzd3vqqzn2x7d**

_nostr-tool -r wss://nostr.wine -p [mynsec] delete-event -e 2aa2b9121a0d946c2a4f1f6f3dccea24d17657b413c2f82bbe13a9f2e13736f4_
Private key: [mynsec]
Public key: npub1qfkcklnmes45z75y7y8dkud5yll8vp5eq5ysk9rmgqdxeasv8unsrfj6kq
Deleted event with id: **note1hj6xe7v7a6msu37cwjzzln87gjkx0q9sqdvqj5rts0y68zzd3vqqzn2x7d**

_nostr-tool -r wss://nostr.mom -p [mynsec] delete-event -e 2aa2b9121a0d946c2a4f1f6f3dccea24d17657b413c2f82bbe13a9f2e13736f4_
Private key: [mynsec]
Public key: npub1qfkcklnmes45z75y7y8dkud5yll8vp5eq5ysk9rmgqdxeasv8unsrfj6kq
Deleted event with id: **note1hj6xe7v7a6msu37cwjzzln87gjkx0q9sqdvqj5rts0y68zzd3vqqzn2x7d**

_nostr-tool -r wss://relay.nostr.bg -p [mynsec] delete-event -e 2aa2b9121a0d946c2a4f1f6f3dccea24d17657b413c2f82bbe13a9f2e13736f4_
Private key: [mynsec]
Public key: npub1qfkcklnmes45z75y7y8dkud5yll8vp5eq5ysk9rmgqdxeasv8unsrfj6kq
Deleted event with id: **note1p9p6nrh5mf2ttyjchehrt3q7qf34g7rhxvr0yny07gjpvyhjzylqnvchw9**

_nostr-tool -r wss://relay.wellorder.net -p [mynsec] delete-event -e 2aa2b9121a0d946c2a4f1f6f3dccea24d17657b413c2f82bbe13a9f2e13736f4_
Private key: [mynsec]
Public key: npub1qfkcklnmes45z75y7y8dkud5yll8vp5eq5ysk9rmgqdxeasv8unsrfj6kq
Deleted event with id: **note1p9p6nrh5mf2ttyjchehrt3q7qf34g7rhxvr0yny07gjpvyhjzylqnvchw9**

**Comment by 0xtrr** [comment]
hmm that's weird, I'll take a look at it

**Comment by 0xtrr** [comment]
The delete profile command seems to work fine for me. I published a kind 1 note, then used that nsec to update metadata, then ran delete-profile with the same nsec. The note is now gone and name is updated to be "Deleted".

Test user: npub1plyfjp47y3mk2wx5seeqag79x9c8a7hx25qxqnutmde8walj3pks0tsc0g

**Comment by SilberWitch** [comment]
The command is missing from the CLI. I tried nsec and hex private keys, same response.

![image](https://github.com/user-attachments/assets/ab84f304-5a37-4bdc-88be-1cc93063e229)

**Comment by SilberWitch** [comment]
Might be different because I'm trying to delete the events, but not the profile metadata. The specific command I'm using is 
`nostr-tool -r wss://nos.lol -p [hex private key] delete-profile --events-only --kinds 1`

**Comment by SilberWitch** [comment]
Tried it without the bit after the command, but it also didn't work. It's not finding the option in the menu.

**Comment by SilberWitch** [comment]
See? It's missing.
![image](https://github.com/user-attachments/assets/0a3e6992-d086-41f1-9d1b-1fbe195fe6ef)

**Comment by SilberWitch** [comment]
Do you know why delete-event is changing noteIDs?

**Comment by 0xtrr** [comment]
Ah, I see now that it's not a part of the 0.5.0 release. I'll release a new version (0.5.1) to publish the latest changes so you can use the delete-profile command. 

> Do you know why delete-event is changing noteIDs?

No, haven't checked that yet but I'll try to take a look at it later today. Seems like a weird bug.

**Comment by 0xtrr** [comment]
I've published 0.5.1 to crates.io now so if you update your nostr-tool install, you should have delete-profile available.

https://crates.io/crates/nostr-tool/0.5.1

**Comment by Silberengel** [comment]
Thanks! :smile:
